services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: php-fpm
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
