services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: php-fpm
    ports:
      - "8089:10000"
    volumes:
      - .:/var/www/html
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
