FROM php:8.3.20-fpm-alpine

# Installer les dépendances Alpine + extensions PHP
RUN apk add --no-cache \
        libpng-dev \
        libjpeg-turbo-dev \
        freetype-dev \
        oniguruma-dev \
        libxml2-dev \
        nginx \
        && docker-php-ext-configure gd --with-freetype --with-jpeg \
        && docker-php-ext-install -j$(nproc) gd pdo pdo_mysql

# Installer Composer depuis l’image officielle
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Créer dossier logs Nginx
RUN mkdir -p /run/nginx

WORKDIR /var/www/html
COPY . .

# Copier la config Nginx spécifique Render
COPY nginx/nginx.dev.conf /etc/nginx/nginx.conf

# Exposer le port obligatoire Render
EXPOSE 80

# Commande de lancement (lance PHP-FPM + nginx en foreground)
CMD sh -c "php-fpm --nodaemonize & nginx -g 'daemon off;'"